// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7dnKjfOWlahVzUccygkMgDQkuxfrcpAI',
    appId: '1:586737170980:web:d59951bca2a39d020a76b1',
    messagingSenderId: '586737170980',
    projectId: 'fir-flutter-codelab-f9a36',
    authDomain: 'fir-flutter-codelab-f9a36.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-f9a36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIn9WHxJZ-Wg1lYAUztlbcW7-BbALqlSg',
    appId: '1:586737170980:android:fd39607f0b7e9de40a76b1',
    messagingSenderId: '586737170980',
    projectId: 'fir-flutter-codelab-f9a36',
    storageBucket: 'fir-flutter-codelab-f9a36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApfIxlxzrgUNENiAOT2sDcGHXG5RO5ZU4',
    appId: '1:586737170980:ios:7a43c6fde99253850a76b1',
    messagingSenderId: '586737170980',
    projectId: 'fir-flutter-codelab-f9a36',
    storageBucket: 'fir-flutter-codelab-f9a36.appspot.com',
    iosClientId:
        '586737170980-q1shn82uc8koo6ra2j4s1d8phph7gnub.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApfIxlxzrgUNENiAOT2sDcGHXG5RO5ZU4',
    appId: '1:586737170980:ios:7a43c6fde99253850a76b1',
    messagingSenderId: '586737170980',
    projectId: 'fir-flutter-codelab-f9a36',
    storageBucket: 'fir-flutter-codelab-f9a36.appspot.com',
    iosClientId:
        '586737170980-q1shn82uc8koo6ra2j4s1d8phph7gnub.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
